# ─────────────────────────────────────────────────────────────────────
#  「✦ HYPERPAPER CONFIG ✦ 」
# ─────────────────────────────────────────────────────────────────────

# ── WALLPAPER ────────────────────────────────────────────────────────
wallpaper {
    monitor =
    path = /home/adi/walls/tsmc.png
}

# ── GENERAL ──────────────────────────────────────────────────────────
splash = false
ipc = on
